version: '3.8'
services:
  database:
    image: postgres:15.1-alpine
    container_name: ylab_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 3s
      timeout: 30s
      retries: 3


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ylab_app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=avdeev97
      - POSTGRES_DB=ylab
      - POSTGRES_HOST=database
      - DATABASE_PORT=5432
    env_file:
      - .env
    ports:
      - '8000:8000'
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
