version: '3.8'
services:
  database_test:
    image: postgres:15.1-alpine
    container_name: ylab_db_test
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 3s
      timeout: 30s
      retries: 3


  app_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ylab_app_test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=database_test
      - DATABASE_PORT=${DATABASE_PORT}

    ports:
      - '8080:8000'
    entrypoint: sh -c "alembic upgrade head && pytest -v"
    depends_on:
      database_test:
        condition: service_healthy
    links:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
