version: '3.8'
services:
  database:
    image: postgres:15.1-alpine
    container_name: ylab_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5435"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 3s
      timeout: 30s
      retries: 3


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ylab_app
    env_file:
      - .env
    ports:
      - '8000:80'
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      database:
        condition: service_healthy
